%% ELE410 - CODIGO PREDICAO PARA MERCADO IMOBILIARIO/DEMANDA DE ENERGIA:
%  FREDERICO CASARA ANTONIAZZI - 26/03/2025
%  UFRGS DOUTORADO - PROFESSOR BAZANELLA

% DESCRIÇÃO:
% CODIGO PARA LER E REALIZAR FITTING COM MINIMOS QUADRADOS DOS DADOS
% FORNECIDOS PELO PROFESSOR, OBJETIVO ESTIMAR O VALOR DO IMOVEL EM NOVO
% HAMBURGO BASEADO NOS DADOS EM mercadoImobiliario_table E PREDIZER A 
% DEMANDA(TOTAL, REGIONAL, ESTADUAL) DE ENERGIA ELETRICA NO BRASIL USANDO 
% OS DADOS EM demandaEletrica_table.


%% INICIANDO O MATLAB:

clc;
clear;
close all;

format short;

%% CARACTERIZACAO DO SOLVER:

% 1 - MINIMOS QUADRADOS TRADICIONAL
% 2 - MINIMOS QUADRADOS RECURSIVOS
solver = 1;

% 1 - SEM ESQUECIMENTO
% 2 - COM ESQUECIMENTO
esquecimento = 1;

% 1 - SEM PONDERACAO
% 2 - COM PONDERACAO
ponderacao = 1;

%% VARIAVEIS GLOBAIS:



%% INPUT DOS DADOS: IMPORTANDO OS DADOS EM FORMATO CSV

% CARREGANDO DADOS IMOBILIARIOS:
mercadoImobiliario_table = readtable('DadosMercadoImobiliarioNH.csv', 'VariableNamingRule', 'preserve');

% CARREGANDO DADOS DA DEMANDA DE ENERGIA ELETRICA:
demandaEletrica_table = readtable('DadosDemandaEletricaBrasil.csv', 'VariableNamingRule', 'preserve');

%% ANALISANDO OS DADOS:



%% VISUALIZANDO A ANALISE DE DADOS:

figure;
plot(mercadoImobiliario_area{:, 1}, mercadoImobiliario_valor{:, 1})

%% CONSTRUINDO O MODELO DE MINIMOS QUADRADOS:

theta = (X'*X)\X'*Y;

%% CODIGO PRINCIPAL:


%% VERIFICANDO OS RESULTADOS:

%% SALVANDO OS RESULTADOS: